export {default as Navbar } from './Navbar'
export {default as Homepage } from '../pages/Homepage'
export {default as Exchanges } from '../pages/Exchanges'
export {default as Cryptocurrencies } from '../pages/Cryptocurrencies'
export {default as CryptoDetails } from '../pages/CryptoDetails'
export {default as News } from '../pages/News'